// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SyncMessage.proto

package com.yjl.rest.message.protos;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.yjl.rest.MESSAGE_TYPES}
   */
  public enum MESSAGE_TYPES
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYNC = 0;</code>
     */
    SYNC(0, 0),
    /**
     * <code>PULL = 1;</code>
     */
    PULL(1, 1),
    ;

    /**
     * <code>SYNC = 0;</code>
     */
    public static final int SYNC_VALUE = 0;
    /**
     * <code>PULL = 1;</code>
     */
    public static final int PULL_VALUE = 1;


    public final int getNumber() { return value; }

    public static MESSAGE_TYPES valueOf(int value) {
      switch (value) {
        case 0: return SYNC;
        case 1: return PULL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MESSAGE_TYPES>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MESSAGE_TYPES>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MESSAGE_TYPES>() {
            public MESSAGE_TYPES findValueByNumber(int number) {
              return MESSAGE_TYPES.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.yjl.rest.message.protos.MessageProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final MESSAGE_TYPES[] VALUES = values();

    public static MESSAGE_TYPES valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MESSAGE_TYPES(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.yjl.rest.MESSAGE_TYPES)
  }

  /**
   * Protobuf enum {@code com.yjl.rest.HTTP_METHODS}
   */
  public enum HTTP_METHODS
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>POST = 0;</code>
     */
    POST(0, 0),
    /**
     * <code>PUT = 1;</code>
     */
    PUT(1, 1),
    /**
     * <code>GET = 2;</code>
     */
    GET(2, 2),
    /**
     * <code>DELETE = 3;</code>
     */
    DELETE(3, 3),
    /**
     * <code>HEAD = 4;</code>
     */
    HEAD(4, 4),
    ;

    /**
     * <code>POST = 0;</code>
     */
    public static final int POST_VALUE = 0;
    /**
     * <code>PUT = 1;</code>
     */
    public static final int PUT_VALUE = 1;
    /**
     * <code>GET = 2;</code>
     */
    public static final int GET_VALUE = 2;
    /**
     * <code>DELETE = 3;</code>
     */
    public static final int DELETE_VALUE = 3;
    /**
     * <code>HEAD = 4;</code>
     */
    public static final int HEAD_VALUE = 4;


    public final int getNumber() { return value; }

    public static HTTP_METHODS valueOf(int value) {
      switch (value) {
        case 0: return POST;
        case 1: return PUT;
        case 2: return GET;
        case 3: return DELETE;
        case 4: return HEAD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HTTP_METHODS>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HTTP_METHODS>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HTTP_METHODS>() {
            public HTTP_METHODS findValueByNumber(int number) {
              return HTTP_METHODS.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.yjl.rest.message.protos.MessageProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final HTTP_METHODS[] VALUES = values();

    public static HTTP_METHODS valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private HTTP_METHODS(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.yjl.rest.HTTP_METHODS)
  }

  public interface MessageTypeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.yjl.rest.MESSAGE_TYPES type = 1;
    /**
     * <code>required .com.yjl.rest.MESSAGE_TYPES type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.yjl.rest.MESSAGE_TYPES type = 1;</code>
     */
    com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES getType();
  }
  /**
   * Protobuf type {@code com.yjl.rest.MessageType}
   */
  public static final class MessageType extends
      com.google.protobuf.GeneratedMessage
      implements MessageTypeOrBuilder {
    // Use MessageType.newBuilder() to construct.
    private MessageType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageType defaultInstance;
    public static MessageType getDefaultInstance() {
      return defaultInstance;
    }

    public MessageType getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES value = com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_MessageType_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_MessageType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yjl.rest.message.protos.MessageProtos.MessageType.class, com.yjl.rest.message.protos.MessageProtos.MessageType.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageType> PARSER =
        new com.google.protobuf.AbstractParser<MessageType>() {
      public MessageType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageType(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<MessageType> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.yjl.rest.MESSAGE_TYPES type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES type_;
    /**
     * <code>required .com.yjl.rest.MESSAGE_TYPES type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.yjl.rest.MESSAGE_TYPES type = 1;</code>
     */
    public com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES getType() {
      return type_;
    }

    private void initFields() {
      type_ = com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES.SYNC;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yjl.rest.message.protos.MessageProtos.MessageType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yjl.rest.message.protos.MessageProtos.MessageType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yjl.rest.MessageType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yjl.rest.message.protos.MessageProtos.MessageTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_MessageType_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_MessageType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yjl.rest.message.protos.MessageProtos.MessageType.class, com.yjl.rest.message.protos.MessageProtos.MessageType.Builder.class);
      }

      // Construct using com.yjl.rest.message.protos.MessageProtos.MessageType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES.SYNC;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_MessageType_descriptor;
      }

      public com.yjl.rest.message.protos.MessageProtos.MessageType getDefaultInstanceForType() {
        return com.yjl.rest.message.protos.MessageProtos.MessageType.getDefaultInstance();
      }

      public com.yjl.rest.message.protos.MessageProtos.MessageType build() {
        com.yjl.rest.message.protos.MessageProtos.MessageType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yjl.rest.message.protos.MessageProtos.MessageType buildPartial() {
        com.yjl.rest.message.protos.MessageProtos.MessageType result = new com.yjl.rest.message.protos.MessageProtos.MessageType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yjl.rest.message.protos.MessageProtos.MessageType) {
          return mergeFrom((com.yjl.rest.message.protos.MessageProtos.MessageType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yjl.rest.message.protos.MessageProtos.MessageType other) {
        if (other == com.yjl.rest.message.protos.MessageProtos.MessageType.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yjl.rest.message.protos.MessageProtos.MessageType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yjl.rest.message.protos.MessageProtos.MessageType) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.yjl.rest.MESSAGE_TYPES type = 1;
      private com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES type_ = com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES.SYNC;
      /**
       * <code>required .com.yjl.rest.MESSAGE_TYPES type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.yjl.rest.MESSAGE_TYPES type = 1;</code>
       */
      public com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES getType() {
        return type_;
      }
      /**
       * <code>required .com.yjl.rest.MESSAGE_TYPES type = 1;</code>
       */
      public Builder setType(com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.yjl.rest.MESSAGE_TYPES type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.yjl.rest.message.protos.MessageProtos.MESSAGE_TYPES.SYNC;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yjl.rest.MessageType)
    }

    static {
      defaultInstance = new MessageType(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.yjl.rest.MessageType)
  }

  public interface SyncMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string tenant = 1;
    /**
     * <code>optional string tenant = 1;</code>
     */
    boolean hasTenant();
    /**
     * <code>optional string tenant = 1;</code>
     */
    String getTenant();
    /**
     * <code>optional string tenant = 1;</code>
     */
    com.google.protobuf.ByteString
        getTenantBytes();

    // optional string collection = 2;
    /**
     * <code>optional string collection = 2;</code>
     */
    boolean hasCollection();
    /**
     * <code>optional string collection = 2;</code>
     */
    String getCollection();
    /**
     * <code>optional string collection = 2;</code>
     */
    com.google.protobuf.ByteString
        getCollectionBytes();

    // optional .com.yjl.rest.HTTP_METHODS method = 3;
    /**
     * <code>optional .com.yjl.rest.HTTP_METHODS method = 3;</code>
     */
    boolean hasMethod();
    /**
     * <code>optional .com.yjl.rest.HTTP_METHODS method = 3;</code>
     */
    com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS getMethod();

    // optional string content = 4;
    /**
     * <code>optional string content = 4;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 4;</code>
     */
    String getContent();
    /**
     * <code>optional string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.yjl.rest.SyncMessage}
   */
  public static final class SyncMessage extends
      com.google.protobuf.GeneratedMessage
      implements SyncMessageOrBuilder {
    // Use SyncMessage.newBuilder() to construct.
    private SyncMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SyncMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SyncMessage defaultInstance;
    public static SyncMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SyncMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SyncMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tenant_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              collection_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS value = com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                method_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_SyncMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_SyncMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yjl.rest.message.protos.MessageProtos.SyncMessage.class, com.yjl.rest.message.protos.MessageProtos.SyncMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SyncMessage> PARSER =
        new com.google.protobuf.AbstractParser<SyncMessage>() {
      public SyncMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<SyncMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string tenant = 1;
    public static final int TENANT_FIELD_NUMBER = 1;
    private Object tenant_;
    /**
     * <code>optional string tenant = 1;</code>
     */
    public boolean hasTenant() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string tenant = 1;</code>
     */
    public String getTenant() {
      Object ref = tenant_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tenant_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tenant = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTenantBytes() {
      Object ref = tenant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tenant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collection = 2;
    public static final int COLLECTION_FIELD_NUMBER = 2;
    private Object collection_;
    /**
     * <code>optional string collection = 2;</code>
     */
    public boolean hasCollection() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string collection = 2;</code>
     */
    public String getCollection() {
      Object ref = collection_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collection_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collection = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCollectionBytes() {
      Object ref = collection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        collection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .com.yjl.rest.HTTP_METHODS method = 3;
    public static final int METHOD_FIELD_NUMBER = 3;
    private com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS method_;
    /**
     * <code>optional .com.yjl.rest.HTTP_METHODS method = 3;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.yjl.rest.HTTP_METHODS method = 3;</code>
     */
    public com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS getMethod() {
      return method_;
    }

    // optional string content = 4;
    public static final int CONTENT_FIELD_NUMBER = 4;
    private Object content_;
    /**
     * <code>optional string content = 4;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string content = 4;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tenant_ = "";
      collection_ = "";
      method_ = com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS.POST;
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTenantBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCollectionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, method_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTenantBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCollectionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, method_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yjl.rest.message.protos.MessageProtos.SyncMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yjl.rest.message.protos.MessageProtos.SyncMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yjl.rest.SyncMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yjl.rest.message.protos.MessageProtos.SyncMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_SyncMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_SyncMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yjl.rest.message.protos.MessageProtos.SyncMessage.class, com.yjl.rest.message.protos.MessageProtos.SyncMessage.Builder.class);
      }

      // Construct using com.yjl.rest.message.protos.MessageProtos.SyncMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tenant_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        collection_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS.POST;
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yjl.rest.message.protos.MessageProtos.internal_static_com_restguice_restguice_SyncMessage_descriptor;
      }

      public com.yjl.rest.message.protos.MessageProtos.SyncMessage getDefaultInstanceForType() {
        return com.yjl.rest.message.protos.MessageProtos.SyncMessage.getDefaultInstance();
      }

      public com.yjl.rest.message.protos.MessageProtos.SyncMessage build() {
        com.yjl.rest.message.protos.MessageProtos.SyncMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yjl.rest.message.protos.MessageProtos.SyncMessage buildPartial() {
        com.yjl.rest.message.protos.MessageProtos.SyncMessage result = new com.yjl.rest.message.protos.MessageProtos.SyncMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tenant_ = tenant_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.collection_ = collection_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yjl.rest.message.protos.MessageProtos.SyncMessage) {
          return mergeFrom((com.yjl.rest.message.protos.MessageProtos.SyncMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yjl.rest.message.protos.MessageProtos.SyncMessage other) {
        if (other == com.yjl.rest.message.protos.MessageProtos.SyncMessage.getDefaultInstance()) return this;
        if (other.hasTenant()) {
          bitField0_ |= 0x00000001;
          tenant_ = other.tenant_;
          onChanged();
        }
        if (other.hasCollection()) {
          bitField0_ |= 0x00000002;
          collection_ = other.collection_;
          onChanged();
        }
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000008;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yjl.rest.message.protos.MessageProtos.SyncMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yjl.rest.message.protos.MessageProtos.SyncMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string tenant = 1;
      private Object tenant_ = "";
      /**
       * <code>optional string tenant = 1;</code>
       */
      public boolean hasTenant() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string tenant = 1;</code>
       */
      public String getTenant() {
        Object ref = tenant_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tenant_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string tenant = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTenantBytes() {
        Object ref = tenant_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tenant_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tenant = 1;</code>
       */
      public Builder setTenant(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tenant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tenant = 1;</code>
       */
      public Builder clearTenant() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tenant_ = getDefaultInstance().getTenant();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tenant = 1;</code>
       */
      public Builder setTenantBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tenant_ = value;
        onChanged();
        return this;
      }

      // optional string collection = 2;
      private Object collection_ = "";
      /**
       * <code>optional string collection = 2;</code>
       */
      public boolean hasCollection() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string collection = 2;</code>
       */
      public String getCollection() {
        Object ref = collection_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collection_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string collection = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCollectionBytes() {
        Object ref = collection_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          collection_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collection = 2;</code>
       */
      public Builder setCollection(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        collection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collection = 2;</code>
       */
      public Builder clearCollection() {
        bitField0_ = (bitField0_ & ~0x00000002);
        collection_ = getDefaultInstance().getCollection();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collection = 2;</code>
       */
      public Builder setCollectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        collection_ = value;
        onChanged();
        return this;
      }

      // optional .com.yjl.rest.HTTP_METHODS method = 3;
      private com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS method_ = com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS.POST;
      /**
       * <code>optional .com.yjl.rest.HTTP_METHODS method = 3;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.yjl.rest.HTTP_METHODS method = 3;</code>
       */
      public com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS getMethod() {
        return method_;
      }
      /**
       * <code>optional .com.yjl.rest.HTTP_METHODS method = 3;</code>
       */
      public Builder setMethod(com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.yjl.rest.HTTP_METHODS method = 3;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000004);
        method_ = com.yjl.rest.message.protos.MessageProtos.HTTP_METHODS.POST;
        onChanged();
        return this;
      }

      // optional string content = 4;
      private Object content_ = "";
      /**
       * <code>optional string content = 4;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yjl.rest.SyncMessage)
    }

    static {
      defaultInstance = new SyncMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.yjl.rest.SyncMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_restguice_restguice_MessageType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_restguice_restguice_MessageType_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_restguice_restguice_SyncMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_restguice_restguice_SyncMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021SyncMessage.proto\022\024com.restguice.pbsearc" +
      "h\"@\n\013MessageType\0221\n\004type\030\001 \002(\0162#.com.sam" +
      "sung.restguice.MESSAGE_TYPES\"v\n\013SyncMessa" +
      "ge\022\016\n\006tenant\030\001 \001(\t\022\022\n\ncollection\030\002 \001(\t\0222" +
      "\n\006method\030\003 \001(\0162\".com.yjl.rest.HT" +
      "TP_METHODS\022\017\n\007content\030\004 \001(\t*#\n\rMESSAGE_T" +
      "YPES\022\010\n\004SYNC\020\000\022\010\n\004PULL\020\001*@\n\014HTTP_METHODS" +
      "\022\010\n\004POST\020\000\022\007\n\003PUT\020\001\022\007\n\003GET\020\002\022\n\n\006DELETE\020\003" +
      "\022\010\n\004HEAD\020\004B4\n#com.yjl.rest.messa" +
      "ge.protosB\rMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_restguice_restguice_MessageType_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_restguice_restguice_MessageType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_restguice_restguice_MessageType_descriptor,
              new String[] { "Type", });
          internal_static_com_restguice_restguice_SyncMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_restguice_restguice_SyncMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_restguice_restguice_SyncMessage_descriptor,
              new String[] { "Tenant", "Collection", "Method", "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
